# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 13.x]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install view deps
        run: cd resources/myresource/client/src/views && yarn install
      - name: Install resource deps
        run: cd resources/myresource && yarn install
      - name: Test views
        run: cd resources/myresource/client/src/views && yarn test
      - name: Build views
        run: cd resources/myresource/client/src/views && yarn build
      - name: Build server/client
        run: cd resources/myresource && yarn build
        env:
          CI: true
